name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY_NAME: YOUR_ACR_NAME
  AZURE_RESOURCE_GROUP: YOUR_RESOURCE_GROUP
  AZURE_KUBERNETES_SERVICE_NAME: YOUR_AKS_NAME
  IMAGE_NAME: todo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.prod -t ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker build -f Dockerfile.prod -t ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
    
    - name: Push Docker image
      run: |
        docker push ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure AKS credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ env.AZURE_KUBERNETES_SERVICE_NAME }}
    
    - name: Deploy to AKS using Helm
      run: |
        helm upgrade --install todo-app ./helm/todo-app \
          --namespace production \
          --create-namespace \
          --set image.tag=${{ github.sha }} \
          --set image.repository=${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}

    - name: Check deployment status
      run: |
        kubectl rollout status deployment/todo-app -n production
        kubectl get pods -n production

